### ISSUE TITLE
Buttons Restyling

### ISSUE THREAD

**Issue by yPiuro** [l2dit/NotesRUs#60]
This is a simple re-styling of the front-end buttons such as: Delete, Upload, Preview, Download

## This is a simple restyle of the upload file button

- [x] Restyle Upload file button

### Before:

![image](https://github.com/l2dit/NotesRUs/assets/95382758/0fa61b41-6844-4630-bc10-d3ecbef1171c)

### After:

![image](https://github.com/l2dit/NotesRUs/assets/95382758/1993bb08-b904-4c82-aad9-dd9b2f0e4bd4)

## This is a simple restyle of the input + button for most of the pages (Delete, View, Download)

- [x] Restyle button.
- [x] Restyle text input field.

### Before:

![image](https://github.com/l2dit/NotesRUs/assets/95382758/7aa874fa-1cd9-4dd8-83aa-1470eef252a1)

### After:

![image](https://github.com/l2dit/NotesRUs/assets/95382758/056671ff-fc50-4307-91ce-ca438665bb28)

![image](https://github.com/l2dit/NotesRUs/assets/95382758/24defb98-02f1-405d-84dc-3aef73608d97)

**Comment by Ellozac** [comment]
![image](https://github.com/l2dit/NotesRUs/assets/104737752/ff652994-f547-414c-bdc3-5e9b7faccb72)
this how the download one etc should look

**Comment by yPiuro** [comment]
Alright I will try to do that
