### ISSUE TITLE
Add Markdown Editor

### ISSUE THREAD

**Issue by Ellozac** [l2dit/NotesRUs#70]
- [ ] Add markdown Editor 

Editor:  
    https://github.com/Ionaru/easy-markdown-editor

**Comment by yPiuro** [comment]
![image](https://github.com/l2dit/NotesRUs/assets/95382758/8cc0c932-1964-4af8-95a0-f6df82bfc0ad)

@NotLiam99

Got it 🙏

**Comment by Notliam99** [comment]
Hi @l2dit/devs with the code rendering #71 & #70 I have found some plugins to improve the rendering of code.

Code highlighting https://rehype-pretty.pages.dev/ This allows for much more extensible code blocks with word highlight and titles ect... Just an all-round nicer plugin.

**Comment by Notliam99** [comment]
> Hi @l2dit/devs with the code rendering #71 & #70 I have found some plugins to improve the rendering of code.
> 
> Code highlighting https://rehype-pretty.pages.dev/ This allows for much more extensible code blocks with word highlight and titles ect... Just an all-round nicer plugin.

it uses https://shiki.style/packages/rehype im not shure what the added features of the mentioned plugin has over the one running under the hood

**Comment by Notliam99** [comment]
[wireframe](https://excalidraw.com/#json=FMbVtPIyGDpoUT-anDdlb,lhEz9eDLRnnOesPJlXL6uA)

**Comment by yPiuro** [comment]
Basic MD editor component, linked branch with all the work on it to issue.
